---
- hosts: all
  become: yes
  tasks:
    # 1. Java 11のインストール 
    - name: Install Java 11
      ansible.builtin.yum:
        name: java-11-amazon-corretto-headless
        state: present

    # 2. デプロイ先ディレクトリの作成 
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: /opt/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    # 3. JARファイルのコピー
    - name: Copy Spring Boot JAR to target
      ansible.builtin.copy:
        src: "{{ lookup('fileglob', './*.jar') | first }}"
        dest: /opt/app/app.jar 
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    # 4. アプリケーションの起動 
    - name: Run Spring Boot Application (detached)
      ansible.builtin.shell: |
        # 既存のプロセスがあれば停止
        pkill -f 'java -jar /opt/app/app.jar' || true
        # バックグラウンドでアプリケーションを起動
        nohup java -jar /opt/app/app.jar > /tmp/app.log 2>&1 &
      args:
        chdir: /opt/app