name: Ansible CI

on:
  workflow_dispatch:  
  pull_request:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yml"

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
     

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i "${{ secrets.EC2_HOST }}," \
            -u ec2-user \
            --private-key ~/.ssh/id_rsa \
            -e 'ansible_python_interpreter=/usr/bin/python3.7' \
            ansible/install_java.yml
