name: Deploy Java to EC2

on:
  push:
    branches:
      - main

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible Galaxy collections
        run: ansible-galaxy collection install amazon.aws

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/install_java.yml
          directory: ./ansible
          inventory: './ansible/inventory.ini'
          key_file: ~/.ssh/id_rsa
          