name: Ansible CI

on:
  workflow_dispatch:   # 手動実行できるようにする（最初はこれが安全）
  pull_request:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yml"

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: pip install ansible boto3 botocore

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i "${{ secrets.EC2_PUBLIC_IP }}," \
            -u ec2-user \
            --private-key <(echo "${{ secrets.SSH_PRIVATE_KEY }}") \
            ansible/install_java.yml

